[project]
name = "assay-dagger"
version = "0.1.0"
requires-python = ">=3.13"
dependencies = ["dagger-io"]

[project.entry-points."dagger.mod"]
main_object = "assay_dagger:Assay"

[build-system]
requires = ["uv_build>=0.8.4,<0.9.0"]
build-backend = "uv_build"

[tool.uv.sources]
dagger-io = { path = "sdk", editable = true }
