"""Assay combines heterogeneous measurements into explainable scores."""

from __future__ import annotations

from assay._version import __version__
from assay.compose import compose
from assay.contracts import (
    AdditiveRequest,
    AdditiveTerm,
    ClampPolicy,
    Component,
    Direction,
    ExplainedComponent,
    Interval,
    Method,
    MinimumRequest,
    NativeScale,
    Operation,
    ScoreRequest,
    ScoreResult,
    WeightedMeanRequest,
    parse_request,
    parse_request_json,
)
from assay.errors import ContractValidationError
from assay.measurement import (
    AgreementMeasurementRequest,
    AgreementMeasurementResult,
    BinaryMeasurementRequest,
    BinaryMeasurementResult,
    BinaryMetricControls,
    MeasurementRequest,
    MeasurementResult,
    OrdinalRating,
    RankingMeasurementRequest,
    RankingMeasurementResult,
    RankingMetricControls,
    RankingQueryInput,
    RelevanceInput,
    UncertaintyControls,
    measure,
    parse_measurement_json,
)
from assay.normalize import normalize

__all__ = [
    "AdditiveRequest",
    "AdditiveTerm",
    "AgreementMeasurementRequest",
    "AgreementMeasurementResult",
    "BinaryMeasurementRequest",
    "BinaryMeasurementResult",
    "BinaryMetricControls",
    "ClampPolicy",
    "Component",
    "ContractValidationError",
    "Direction",
    "ExplainedComponent",
    "Interval",
    "MeasurementRequest",
    "MeasurementResult",
    "Method",
    "MinimumRequest",
    "NativeScale",
    "Operation",
    "OrdinalRating",
    "RankingMeasurementRequest",
    "RankingMeasurementResult",
    "RankingMetricControls",
    "RankingQueryInput",
    "RelevanceInput",
    "ScoreRequest",
    "ScoreResult",
    "UncertaintyControls",
    "WeightedMeanRequest",
    "__version__",
    "compose",
    "measure",
    "normalize",
    "parse_measurement_json",
    "parse_request",
    "parse_request_json",
]
