"""Literals the docs promise, pinned to the literal — not to themselves.

A constant asserted only against its own source is unguarded: ``assert
settings.ranking_k == AssaySettings().ranking_k`` holds at every value, and a test
shaped that way stays green through the exact change it exists to catch. Every
assertion here writes the number the documentation states out loud, so changing the
default without changing the docs fails here.

These sit apart from ``test_settings.py`` on purpose: that file tests the settings
mechanism (defaults exist, env overrides win), this one tests that specific published
promises are still true.
"""

from __future__ import annotations

import importlib.util
import json
import sys
from pathlib import Path

from assay.settings import AssaySettings


def _load_mutation_harness() -> object:
    """Import `scripts/mutation_harness.py` by path.

    `scripts/` is not an installed package — it is held to the gate but not shipped —
    so there is no import name for it. Loading it by location beats putting the repo
    root on `sys.path` from inside a test.

    The `sys.modules` registration is not optional: `@dataclass` resolves a field's
    annotations by looking its own module up there, and a module that was executed
    without being registered raises `AttributeError` on the first frozen dataclass.
    It is removed again so nothing else in the session sees a half-real import."""
    spec = importlib.util.spec_from_file_location("mutation_harness", _HARNESS)
    assert spec is not None
    assert spec.loader is not None
    module = importlib.util.module_from_spec(spec)
    sys.modules[spec.name] = module
    try:
        spec.loader.exec_module(module)
    finally:
        sys.modules.pop(spec.name, None)
    return module


_CANONICAL = Path("testdata/vectors/canonical.json")
_RECEIPTS = Path("testdata/vectors/receipts.json")
_METRICS = Path("testdata/vectors/metrics.json")
_HARNESS = Path("scripts/mutation_harness.py")

# README, "How the guards are proved": "scripts/mutation_harness.py lists all 36 with the
# claim each one breaks". Pinned because this number had already drifted once — the README
# said 18 while the harness carried 19, and nothing was counting.
_DOCUMENTED_MUTATIONS = 36

# README, "Key custody and cross-language vectors": "testdata/vectors/ holds 12 golden
# vectors generated by tests/gen_vectors.py: 9 canonicalization cases ... and 3 receipts".
_DOCUMENTED_CANONICAL_VECTORS = 9
_DOCUMENTED_RECEIPT_VECTORS = 3
_DOCUMENTED_TOTAL_VECTORS = 12

# README, same section: "metrics.json holds 22 hand-computed metric cases: 6 ranking and
# 7 ranking refusals, 5 classification and 4 classification refusals".
_DOCUMENTED_METRIC_CASES = {
    "ranking": 6,
    "ranking_refusals": 7,
    "classification": 5,
    "classification_refusals": 4,
}
_DOCUMENTED_METRIC_TOTAL = 22

# src/assay/ranking.py: "10 is the conventional 'first page' depth".
_DOCUMENTED_RANKING_K = 10


def test_the_golden_vector_counts_the_readme_promises() -> None:
    # Given the two golden-vector files the README describes by count
    canonical = json.loads(_CANONICAL.read_text(encoding="utf-8"))
    receipts = json.loads(_RECEIPTS.read_text(encoding="utf-8"))["receipts"]
    # When they are counted
    # Then the counts are exactly the ones the README states. The sibling assertions in
    # test_vectors.py are `>= 8` and `>= 1` — deliberately loose bounds on *shape*, which
    # stay green while three vectors quietly go missing and the README keeps saying 12.
    assert len(canonical) == _DOCUMENTED_CANONICAL_VECTORS
    assert len(receipts) == _DOCUMENTED_RECEIPT_VECTORS
    assert len(canonical) + len(receipts) == _DOCUMENTED_TOTAL_VECTORS


def test_the_metric_vector_counts_the_readme_promises() -> None:
    # Given the shared metric vectors both language suites replay
    metrics = json.loads(_METRICS.read_text(encoding="utf-8"))
    # When each section is counted
    # Then the counts are exactly the ones the README states. The sibling assertions in
    # the two replay suites are `>= 6` and `>= 5` — loose bounds on shape, which stay
    # green while a case quietly goes missing from one language's coverage.
    for section, documented in _DOCUMENTED_METRIC_CASES.items():
        assert len(metrics[section]) == documented, section
    assert sum(len(metrics[s]) for s in _DOCUMENTED_METRIC_CASES) == _DOCUMENTED_METRIC_TOTAL


def test_the_mutation_count_the_readme_promises() -> None:
    # Given the mutation harness the README describes by count
    harness = _load_mutation_harness()
    # When its mutations are counted
    # Then there are exactly as many as the README claims. Every guard is a claim, so a
    # mutation added without a sentence to explain it is a claim nobody can read.
    assert len(harness.MUTATIONS) == _DOCUMENTED_MUTATIONS  # type: ignore[attr-defined]


def test_the_default_ranking_cutoff_the_docs_promise() -> None:
    # Given settings with no ASSAY_* overrides
    settings = AssaySettings()
    # When the ranking cut-off is read
    # Then it is the documented first-page depth, written here as the literal 10 so the
    # default cannot drift away from the sentence that explains it.
    assert settings.ranking_k == _DOCUMENTED_RANKING_K
